spring:
  profiles:
    active: default
  application:
    name: serviceofferings-orchestrator
  datasource:
    url: jdbc:h2:file:./database.db
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    generate-ddl: true
    ddl:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8084'
  servlet:
    context-path: /api
  error:
    include-stacktrace: "never"
    include-message: "always"

gxfscatalog:
  base-uri: "http://localhost:8081"
  selfdescriptions-uri: "${gxfscatalog.base-uri}/self-descriptions"
  private-key-path: ""
  cert-path: ""
  verification-method: "did:web:compliance.lab.gaia-x.eu"

gxfswizardapi:
  base-uri: "http://localhost:8085"

organizations-orchestrator:
  base-uri: http://localhost:8082/api

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

keycloak:
  client-id: "federated-catalogue"
  authorization-grant-type: "password"
  base-uri: "http://key-server:8080"
  oidc-base-uri: "${keycloak.base-uri}/realms/gxfscatalog/protocol/openid-connect"
  token-uri: "${keycloak.oidc-base-uri}/token"
  logout-uri: "${keycloak.oidc-base-uri}/logout"
  client-secret: "CScowEqRGIb6d7SLCZHVjKHIewp0ZmnO"
  gxfscatalog-user: "gxfscatalog"
  gxfscatalog-pass: "gxfscatalog"

cors:
  global:
    origins:
    patterns: >
      http://localhost:[*]

merlot-domain: "localhost"

gxfscatalog-library:
  ignore-ssl: true

gxdch-services:
  compliance-base-uris:
    "https://compliance.lab.gaia-x.eu" #,
    #"https://gx-compliance.aruba.it",
    #"https://gx-compliance.gxdch.dih.telekom.com",
  #"https://gx-compliance.airenetworks.es"
  registry-base-uris:
    "https://registry.lab.gaia-x.eu" #,
    #"https://gx-registry.aruba.it",
    #"https://gx-registry.gxdch.dih.telekom.com",
  #"https://gx-registry.airenetworks.es"
  notary-base-uris:
    "https://registrationnumber.notary.lab.gaia-x.eu" #,
    #"https://gx-notary.aruba.it",
    #"https://gx-notary.gxdch.dih.telekom.com",
  #"https://gx-notary.airenetworks.es"
  version: "v1-staging"
