cors:
  global:
    origins: >
      https://marketplace.dev.merlot-education.eu,
      https://api.dev.merlot-education.eu
    patterns:

merlot-domain: "marketplace.dev.merlot-education.eu"

spring:
  h2:
    console.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-service.dev.merlot-education.eu
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks
          userinfo-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/userinfo
          
jwt-auth-converter: ssiJwtAuthConverter

gxfscatalog-library:
  ignore-ssl: false

gxdch-services:
  enforce-compliance: true
  enforce-notary: true
  compliance-base-uris:
    "https://compliance.lab.gaia-x.eu/v1-staging" #,
  #"https://gx-compliance.aruba.it",
  #"https://gx-compliance.gxdch.dih.telekom.com",
  #"https://gx-compliance.airenetworks.es"
  registry-base-uris:
    "https://registry.lab.gaia-x.eu/v1-staging" #,
  #"https://gx-registry.aruba.it",
  #"https://gx-registry.gxdch.dih.telekom.com",
  #"https://gx-registry.airenetworks.es"
  notary-base-uris:
    "https://registrationnumber.notary.lab.gaia-x.eu/development" #,
  #"https://gx-notary.aruba.it",
  #"https://gx-notary.gxdch.dih.telekom.com",
  #"https://gx-notary.airenetworks.es"
