spring:
  profiles:
    active: default
  application:
    name: serviceofferings-orchestrator
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://key-server:8080/realms/POC1
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:h2:file:./database.db
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    generate-ddl: true
    ddl:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

jwt:
  auth:
    converter:
      resource-id: MARKETPLACE
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8084'
  servlet:
    context-path: /api
  error:
    include-stacktrace: "never"
    include-message: "always"

gxfscatalog:
  base-uri: "http://localhost:8081"
  selfdescriptions-uri: "${gxfscatalog.base-uri}/self-descriptions"
  private-key-path: "${user.home}/workspace/mpo/merlot-cert/prk.ss.pem"
  cert-path: "${user.home}/workspace/mpo/merlot-cert/cert.ss.pem"
  verification-method: "did:web:merlot-education.eu"

gxfswizardapi:
  base-uri: "http://localhost:8085"

organizations-orchestrator:
  base-uri: http://localhost:8082/api

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

keycloak:
  client-id: "federated-catalogue"
  authorization-grant-type: "password"
  base-uri: "http://key-server:8080"
  oidc-base-uri: "${keycloak.base-uri}/realms/gxfscatalog/protocol/openid-connect"
  authorization-uri: "${keycloak.oidc-base-uri}/auth"
  token-uri: "${keycloak.oidc-base-uri}/token"
  logout-uri: "${keycloak.oidc-base-uri}/logout"
  jwk-set-uri: "${keycloak.oidc-base-uri}/certs"
  client-secret: "NnyjZISWVHa9zamW8XEGsSuH6pbtXLmg"
  gxfscatalog-user: "gxfscatalog"
  gxfscatalog-pass: "gxfscatalog"

cors:
  global:
    origins:
    patterns: >
      http://localhost:[*]

merlot-domain: "localhost"

gxfscatalog-library:
  ignore-ssl: true