cors:
  global:
    origins: >
      https://marketplace.demo.merlot-education.eu,
      https://api.demo.merlot-education.eu
    patterns:

merlot-domain: "marketplace.demo.merlot-education.eu"

gxfscatalog-library:
  ignore-ssl: false