cors:
  global:
    origins: >
      https://marketplace.dev.merlot-education.eu,
      https://api.dev.merlot-education.eu
    patterns:

merlot-domain: "marketplace.dev.merlot-education.eu"

spring:
  h2:
    console.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth-service.dev.merlot-education.eu
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/oauth2/jwks
          userinfo-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/userinfo
          
jwt-auth-converter: ssiJwtAuthConverter

gxfscatalog-library:
  ignore-ssl: false
