spring:
  application:
    name: serviceofferings-orchestrator
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso.common.merlot-education.eu/realms/POC1
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:h2:file:./database.db
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    generate-ddl: true
    ddl:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

jwt:
  auth:
    converter:
      resource-id: MARKETPLACE
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8084'
  servlet:
    context-path: /api
  error:
    include-stacktrace: "never"

gxfscatalog:
  base-uri: "http://localhost:8081"
  selfdescriptions-uri: "${gxfscatalog.base-uri}/self-descriptions"

keycloak:
  client-id: "federated-catalogue"
  authorization-grant-type: "password"
  base-uri: "http://key-server:8080"
  oidc-base-uri: "${keycloak.base-uri}/realms/gaia-x/protocol/openid-connect"
  authorization-uri: "${keycloak.oidc-base-uri}/auth"
  token-uri: "${keycloak.oidc-base-uri}/token"
  logout-uri: "${keycloak.oidc-base-uri}/logout"
  jwk-set-uri: "${keycloak.oidc-base-uri}/certs"
  client-secret: "510kJDtoXbEmiPNwBacCnLmDGgtB0gjm"
  gxfscatalog-user: "gxfscatalog"
  gxfscatalog-pass: "gxfscatalog"